version: '4'
services:
  mongodb1:
    image: mongo:7.0.5
    container_name: mongodb-food
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data/mongodb1:/data/db
  mongodb3:
    image: mongo:7.0.5
    container_name: mongodb-review
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: review-service
    volumes:
      - ./data/mongodb3:/data/db
  mongodb4:
    image: mongo:7.0.5
    container_name: mongodb-restaurant
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rest-service
    volumes:
      - ./data/mongodb4:/data/db
  mongodb5:
    image: mongo:7.0.5
    container_name: mongodb-recommendations
    ports:
      - "27021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: recommendation-service
    volumes:
      - ./data/mongodb5:/data/db
  mongodb6:
    image: mongo:7.0.5
    container_name: mongodb-hangout
    ports:
      - "27022:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hangout-service
    volumes:
      - ./data/mongodb6:/data/db
  postgres-kc:
    image: postgres:17.6
    container_name: postgres-kc 
    volumes:
      - ./data/postgres-kc:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_db_user
      POSTGRES_PASSWORD: keycloak_db_user_password
  postgres-user:
    image: postgres:17.6
    container_name: postgres-user 
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres-user:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      interval: 5s
      retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start --import-realm
    environment:
      KC_HOSTNAME: http://keycloak:8080
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-kc/keycloak_db
      KC_DB_USERNAME: keycloak_db_user
      KC_DB_PASSWORD: keycloak_db_user_password
    ports:
      - 8090:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - postgres-kc
  nginx-proxy:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
  image-service-sb:
    image: sleepytmzd/image-service-sb:v3      
    container_name: image-service-sb 
    ports:
      - "8085:8080"
    environment:
      # cloudinary url must be supplied in .env
      CLOUDINARY_URL: "${CLOUDINARY_URL}"
  food-service:
    image: sleepytmzd/food-service:v5
    container_name: food-service
    ports:
      - "8081:8081"
    environment:
      RECOM_SERVICE_URL: http://recomm-agent-service:8020
      RESTAURANT_SERVICE_URL: http://restaurant-service:8089
      IMAGE_SERVICE_URL: http://image-service-sb:8080
      MONGODB1_URL: mongodb://root:password@mongodb1:27017/product-service?authSource=admin
      FRONTEND_URL: http://localhost:7000
      KC_ISSUER_URL: http://keycloak:8080/realms/foodhub
    depends_on:
      - mongodb1
      - image-service-sb
      - recomm-agent-service
  review-service:
    image: sleepytmzd/review-service:v5
    container_name: review-service
    ports:
      - "8083:8083"
    environment:
      NEGPOS_URL: http://negative-positive-agent-service:8021
      MONGODB3_URL: mongodb://root:password@mongodb3:27017/review-service?authSource=admin
      FRONTEND_URL: http://localhost:7000
      KC_ISSUER_URL: http://keycloak:8080/realms/foodhub
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - mongodb3
  user-service:
    image: sleepytmzd/user-service:v6
    container_name: user-service 
    ports:
      - "8084:8084"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-user:5432/user_db
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password
      IMAGE_SERVICE_URL: http://image-service-sb:8080
      FRONTEND_URL: http://localhost:7000
      KC_ISSUER_URL: http://keycloak:8080/realms/foodhub
      STARTING_COINS: 20
    depends_on:
      postgres-user:
        condition: service_healthy
  restaurant-service:
    image: sleepytmzd/restaurant-service:v1
    container_name: restaurant-service
    ports:
      - "8089:8089"
    environment:
      RECOM_SERVICE_URL: http://recomm-agent-service:8020
      MONGODB4_URL: mongodb://root:password@mongodb4:27017/rest-service?authSource=admin
      FRONTEND_URL: http://localhost:7000
      KC_ISSUER_URL: http://keycloak:8080/realms/foodhub
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - mongodb4
      - recomm-agent-service
  frontend:
    image: sleepytmzd/frontend:v5
    container_name: frontend
    ports:
      - "7000:7000"
    environment:
      NEXT_PUBLIC_KEYCLOAK_URL: http://localhost:8080
      NEXT_PUBLIC_KEYCLOAK_REALM: foodhub
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: foodhub-kc
      NEXT_PUBLIC_USER_SERVICE_URL: http://localhost:8084
      NEXT_PUBLIC_REVIEW_SERVICE_URL: http://localhost:8083
      NEXT_PUBLIC_FOOD_SERVICE_URL: http://localhost:8081
      NEXT_PUBLIC_RECOMM_AGENT_URL: http://localhost:8020
      NEXT_PUBLIC_RESTAURANT_SERVICE_URL: http://localhost:8089
      NEXT_PUBLIC_NUTRITION_AGENT_URL: http://localhost:8022
      NEXT_PUBLIC_HANGOUT_SERVICE_URL: http://localhost:8091
    depends_on:
      - keycloak
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
  recomm-agent-service:
    image: sleepytmzd/recomm-agent:v2
    container_name: recomm-agent-service
    ports:
      - "8020:8020"
    environment:
      QDRANT_URL: http://qdrant:6333
      MONGODB5_URL: mongodb://root:password@mongodb5:27017/recommendation-service?authSource=admin
      # API keys moved to .env
      GOOGLE_PLACES_API_KEY: "${GOOGLE_PLACES_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      FRONTEND_URL: http://localhost:7000
    depends_on:
      - qdrant
  negative-positive-agent-service:
    image: sleepytmzd/negative-positive-agent:v1
    container_name: negative-positive-agent-service
    ports:
      - "8021:8021"
    environment:
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
  nutrition-predict-agent:
    image: sleepytmzd/nutrition-predict-agent:v1
    container_name: nutrition-predict-agent
    ports:
      - "8022:8022"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      FRONTEND_URL: http://localhost:7000
  hangout-service:
    image: sleepytmzd/hangout-service:v1
    container_name: hangout-service
    ports:
      - "8091:8091"
    environment:
      MONGODB6_URL: mongodb://root:password@mongodb6:27017/hangout-service?authSource=admin
      FRONTEND_URL: http://localhost:7000
      KC_ISSUER_URL: http://keycloak:8080/realms/foodhub
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - mongodb6
