apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-service-deployment
  labels:
    app: food-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-service
  template:
    metadata:
      labels:
        app: food-service
    spec:
      containers:
      - name: food-service
        image: sleepytmzd/food-service:v1
        ports:
        - containerPort: 8081
        env:
        - name: IMAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config 
              key: image-service-url
        - name: MONGODB_URL
          value: mongodb://root:password@mongodb-food-service:27017/product-service?authSource=admin

---

apiVersion: v1
kind: Service
metadata:
  name: food-service-service
spec:
  type: NodePort
  selector:
    app: food-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100

