apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sleepytmzd/frontend:v5
        ports:
        - containerPort: 7000
        env:
        - name: NEXT_PUBLIC_KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: app-config 
              key: keycloak-url
        - name: NEXT_PUBLIC_KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: app-config 
              key: keycloak-realm
        - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config 
              key: keycloak-client-id
        - name: NEXT_PUBLIC_RESTAURANT_SERVICE_URL
          value: ""
        - name: NEXT_PUBLIC_USER_SERVICE_URL
          value: ""
        - name: NEXT_PUBLIC_REVIEW_SERVICE_URL
          value: ""
        - name: NEXT_PUBLIC_FOOD_SERVICE_URL
          value: ""
        - name: NEXT_PUBLIC_HANGOUT_SERVICE_URL
          value: ""
        - name: NEXT_PUBLIC_RECOMM_AGENT_URL
          value: ""
        - name: NEXT_PUBLIC_NUTRITION_AGENT_URL
          value: ""
              
        resources:
          requests:
            cpu: "100m"       
            memory: "256Mi"  
          limits:
            cpu: "200m"       
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      # nodePort: 30100

