apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-food-deployment
  labels:
    app: mongodb-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-food
  template:
    metadata:
      labels:
        app: mongodb-food
    spec:
      containers:
      - name: mongodb-food
        image: mongo:7.0.5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: mongo-user 
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: mongo-password
        - name: MONGO_INITDB_DATABASE
          value: product-service
        resources:
          requests:
            cpu: "100m"     
            memory: "250Mi"  
          limits:
            cpu: "500m"    
            memory: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-food-service
spec:
  selector:
    app: mongodb-food
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

