apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-kc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-kc-deployment
  labels:
    app: postgres-kc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-kc
  template:
    metadata:
      labels:
        app: postgres-kc
    spec:
      containers:
      - name: postgres-kc
        image: postgres:17.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: keycloak_db
        - name: POSTGRES_USER
          value: keycloak_db_user
        - name: POSTGRES_PASSWORD
          value: keycloak_db_user_password
        resources:
          requests:
            cpu: "100m"     
            memory: "250Mi"  
          limits:
            cpu: "500m"    
            memory: "1Gi"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/kc/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-kc-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-kc-service
spec:
  selector:
    app: postgres-kc
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

