apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-service-deployment
  labels:
    app: visit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-service
  template:
    metadata:
      labels:
        app: visit-service
    spec:
      containers:
      - name: visit-service
        image: sleepytmzd/visit-service:v2
        ports:
        - containerPort: 8082
        env:
        - name: MONGODB2_URL
          value: mongodb://root:password@mongodb-visit-service:27017/visit-service?authSource=admin
        resources:
          requests:
            cpu: "100m"       
            memory: "256Mi"  
          limits:
            cpu: "200m"       
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: visit-service-service
spec:
  type: NodePort
  selector:
    app: visit-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      # nodePort: 30100

