name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push Docker images for all services
      - name: Build and Push Images
        run: |
          # Define your services and their directories
          SERVICES=("food-service" "image-service-sb")

          for SERVICE in "${SERVICES[@]}"; do
            echo "Building $SERVICE ..."
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE:latest"
            
            docker build -t $IMAGE_NAME ./$SERVICE
            docker push $IMAGE_NAME
          done
